import { Category, InventoryItem, Shop, Order } from "./types";

export const categories: Category[] = [
  { id: "cat-1", name: "Produce", image: "/placeholder-item.svg" },
  { id: "cat-2", name: "Dairy", image: "/placeholder-item.svg" },
  { id: "cat-3", name: "Beverages", image: "/placeholder-item.svg" },
  { id: "cat-4", name: "Snacks", image: "/placeholder-item.svg" },
  { id: "cat-5", name: "Frozen", image: "/placeholder-item.svg" },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "item-1",
    name: "Organic Bananas (40lb case)",
    image: "/placeholder-item.svg",
    price: 24.99,
    quantity: 120,
    expirationDate: "2026-03-15",
    categoryId: "cat-1",
  },
  {
    id: "item-2",
    name: "Roma Tomatoes (25lb box)",
    image: "/placeholder-item.svg",
    price: 18.5,
    quantity: 85,
    expirationDate: "2026-03-08",
    categoryId: "cat-1",
  },
  {
    id: "item-3",
    name: "Russet Potatoes (50lb sack)",
    image: "/placeholder-item.svg",
    price: 15.0,
    quantity: 6,
    expirationDate: "2026-04-20",
    categoryId: "cat-1",
  },
  {
    id: "item-4",
    name: "Whole Milk (4gal case)",
    image: "/placeholder-item.svg",
    price: 14.99,
    quantity: 48,
    expirationDate: "2026-03-10",
    categoryId: "cat-2",
  },
  {
    id: "item-5",
    name: "Cheddar Cheese Block (5lb)",
    image: "/placeholder-item.svg",
    price: 22.0,
    quantity: 3,
    expirationDate: "2026-05-01",
    categoryId: "cat-2",
  },
  {
    id: "item-6",
    name: "Greek Yogurt (12-pack)",
    image: "/placeholder-item.svg",
    price: 11.99,
    quantity: 60,
    expirationDate: "2026-03-20",
    categoryId: "cat-2",
  },
  {
    id: "item-7",
    name: "Spring Water (24-pack)",
    image: "/placeholder-item.svg",
    price: 4.99,
    quantity: 200,
    expirationDate: "2027-06-01",
    categoryId: "cat-3",
  },
  {
    id: "item-8",
    name: "Orange Juice (12x1L)",
    image: "/placeholder-item.svg",
    price: 28.0,
    quantity: 8,
    expirationDate: "2026-03-25",
    categoryId: "cat-3",
  },
  {
    id: "item-9",
    name: "Cola Cans (24-pack)",
    image: "/placeholder-item.svg",
    price: 9.99,
    quantity: 150,
    expirationDate: "2026-12-01",
    categoryId: "cat-3",
  },
  {
    id: "item-10",
    name: "Tortilla Chips (16oz, 12-pack)",
    image: "/placeholder-item.svg",
    price: 19.99,
    quantity: 45,
    expirationDate: "2026-07-15",
    categoryId: "cat-4",
  },
  {
    id: "item-11",
    name: "Mixed Nuts (5lb bag)",
    image: "/placeholder-item.svg",
    price: 32.0,
    quantity: 2,
    expirationDate: "2026-09-01",
    categoryId: "cat-4",
  },
  {
    id: "item-12",
    name: "Granola Bars (48-count)",
    image: "/placeholder-item.svg",
    price: 16.5,
    quantity: 70,
    expirationDate: "2026-08-30",
    categoryId: "cat-4",
  },
  {
    id: "item-13",
    name: "Frozen Chicken Breast (10lb)",
    image: "/placeholder-item.svg",
    price: 27.99,
    quantity: 35,
    expirationDate: "2026-09-15",
    categoryId: "cat-5",
  },
  {
    id: "item-14",
    name: "Frozen Mixed Vegetables (5lb)",
    image: "/placeholder-item.svg",
    price: 8.99,
    quantity: 90,
    expirationDate: "2026-11-01",
    categoryId: "cat-5",
  },
  {
    id: "item-15",
    name: "Ice Cream Tubs (4gal)",
    image: "/placeholder-item.svg",
    price: 19.99,
    quantity: 5,
    expirationDate: "2026-06-01",
    categoryId: "cat-5",
  },
];

export const shops: Shop[] = [
  {
    id: "shop-1",
    name: "Green Valley Market",
    owner: "Maria Santos",
    location: "142 Oak Street, Springfield, IL 62701",
    phone: "(217) 555-0134",
    openingTime: "07:00",
    closingTime: "19:00",
  },
  {
    id: "shop-2",
    name: "Metro Fresh Foods",
    owner: "David Chen",
    location: "890 Commerce Blvd, Springfield, IL 62704",
    phone: "(217) 555-0267",
    openingTime: "06:00",
    closingTime: "20:00",
  },
  {
    id: "shop-3",
    name: "Sunrise Grocery",
    owner: "Amara Obi",
    location: "2201 Lincoln Ave, Springfield, IL 62702",
    phone: "(217) 555-0389",
    openingTime: "08:00",
    closingTime: "18:00",
  },
  {
    id: "shop-4",
    name: "Corner Basket Deli",
    owner: "James Kowalski",
    location: "55 Main Street, Springfield, IL 62701",
    phone: "(217) 555-0412",
    openingTime: "09:00",
    closingTime: "17:00",
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    shopId: "shop-1",
    date: "2026-02-25",
    lineItems: [
      { itemId: "item-1", itemName: "Organic Bananas (40lb case)", quantity: 5, unitPrice: 24.99 },
      { itemId: "item-4", itemName: "Whole Milk (4gal case)", quantity: 10, unitPrice: 14.99 },
      { itemId: "item-7", itemName: "Spring Water (24-pack)", quantity: 20, unitPrice: 4.99 },
    ],
    total: 374.65,
  },
  {
    id: "ord-2",
    shopId: "shop-1",
    date: "2026-02-20",
    lineItems: [
      { itemId: "item-2", itemName: "Roma Tomatoes (25lb box)", quantity: 8, unitPrice: 18.5 },
      { itemId: "item-10", itemName: "Tortilla Chips (16oz, 12-pack)", quantity: 6, unitPrice: 19.99 },
    ],
    total: 267.94,
  },
  {
    id: "ord-3",
    shopId: "shop-2",
    date: "2026-02-24",
    lineItems: [
      { itemId: "item-9", itemName: "Cola Cans (24-pack)", quantity: 30, unitPrice: 9.99 },
      { itemId: "item-12", itemName: "Granola Bars (48-count)", quantity: 15, unitPrice: 16.5 },
      { itemId: "item-13", itemName: "Frozen Chicken Breast (10lb)", quantity: 12, unitPrice: 27.99 },
    ],
    total: 883.08,
  },
  {
    id: "ord-4",
    shopId: "shop-2",
    date: "2026-02-18",
    lineItems: [
      { itemId: "item-6", itemName: "Greek Yogurt (12-pack)", quantity: 20, unitPrice: 11.99 },
      { itemId: "item-14", itemName: "Frozen Mixed Vegetables (5lb)", quantity: 25, unitPrice: 8.99 },
    ],
    total: 464.55,
  },
  {
    id: "ord-5",
    shopId: "shop-3",
    date: "2026-02-26",
    lineItems: [
      { itemId: "item-3", itemName: "Russet Potatoes (50lb sack)", quantity: 4, unitPrice: 15.0 },
      { itemId: "item-5", itemName: "Cheddar Cheese Block (5lb)", quantity: 8, unitPrice: 22.0 },
      { itemId: "item-8", itemName: "Orange Juice (12x1L)", quantity: 6, unitPrice: 28.0 },
    ],
    total: 404.0,
  },
  {
    id: "ord-6",
    shopId: "shop-3",
    date: "2026-02-15",
    lineItems: [
      { itemId: "item-11", itemName: "Mixed Nuts (5lb bag)", quantity: 3, unitPrice: 32.0 },
      { itemId: "item-15", itemName: "Ice Cream Tubs (4gal)", quantity: 10, unitPrice: 19.99 },
    ],
    total: 295.9,
  },
  {
    id: "ord-7",
    shopId: "shop-4",
    date: "2026-02-22",
    lineItems: [
      { itemId: "item-1", itemName: "Organic Bananas (40lb case)", quantity: 3, unitPrice: 24.99 },
      { itemId: "item-2", itemName: "Roma Tomatoes (25lb box)", quantity: 5, unitPrice: 18.5 },
      { itemId: "item-4", itemName: "Whole Milk (4gal case)", quantity: 6, unitPrice: 14.99 },
    ],
    total: 257.41,
  },
  {
    id: "ord-8",
    shopId: "shop-4",
    date: "2026-02-10",
    lineItems: [
      { itemId: "item-7", itemName: "Spring Water (24-pack)", quantity: 40, unitPrice: 4.99 },
      { itemId: "item-9", itemName: "Cola Cans (24-pack)", quantity: 20, unitPrice: 9.99 },
    ],
    total: 399.4,
  },
];
