import { Category, InventoryItem, Shop, Order } from "./types";

export const categories: Category[] = [
  { id: "cat-1", name: "Produce", image: "/placeholder-item.svg" },
  { id: "cat-2", name: "Dairy", image: "/placeholder-item.svg" },
  { id: "cat-3", name: "Beverages", image: "/placeholder-item.svg" },
  { id: "cat-4", name: "Snacks", image: "/placeholder-item.svg" },
  { id: "cat-5", name: "Frozen", image: "/placeholder-item.svg" },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "item-1",
    name: "Organic Bananas (18kg case)",
    image: "/placeholder-item.svg",
    price: 21.99,
    quantity: 120,
    expirationDate: "2026-03-15",
    categoryId: "cat-1",
  },
  {
    id: "item-2",
    name: "Vine Tomatoes (10kg box)",
    image: "/placeholder-item.svg",
    price: 16.50,
    quantity: 85,
    expirationDate: "2026-03-08",
    categoryId: "cat-1",
  },
  {
    id: "item-3",
    name: "Maris Piper Potatoes (25kg sack)",
    image: "/placeholder-item.svg",
    price: 12.00,
    quantity: 6,
    expirationDate: "2026-04-20",
    categoryId: "cat-1",
  },
  {
    id: "item-4",
    name: "Semi-Skimmed Milk (12x2L)",
    image: "/placeholder-item.svg",
    price: 13.99,
    quantity: 48,
    expirationDate: "2026-03-10",
    categoryId: "cat-2",
  },
  {
    id: "item-5",
    name: "Cathedral City Cheddar (2.5kg block)",
    image: "/placeholder-item.svg",
    price: 18.50,
    quantity: 3,
    expirationDate: "2026-05-01",
    categoryId: "cat-2",
  },
  {
    id: "item-6",
    name: "Greek Yoghurt (12-pack)",
    image: "/placeholder-item.svg",
    price: 10.99,
    quantity: 60,
    expirationDate: "2026-03-20",
    categoryId: "cat-2",
  },
  {
    id: "item-7",
    name: "Highland Spring Water (24-pack)",
    image: "/placeholder-item.svg",
    price: 4.49,
    quantity: 200,
    expirationDate: "2027-06-01",
    categoryId: "cat-3",
  },
  {
    id: "item-8",
    name: "Tropicana Orange Juice (12x1L)",
    image: "/placeholder-item.svg",
    price: 24.00,
    quantity: 8,
    expirationDate: "2026-03-25",
    categoryId: "cat-3",
  },
  {
    id: "item-9",
    name: "Coca-Cola Cans (24-pack)",
    image: "/placeholder-item.svg",
    price: 8.99,
    quantity: 150,
    expirationDate: "2026-12-01",
    categoryId: "cat-3",
  },
  {
    id: "item-10",
    name: "Walkers Crisps Variety (48-pack)",
    image: "/placeholder-item.svg",
    price: 17.99,
    quantity: 45,
    expirationDate: "2026-07-15",
    categoryId: "cat-4",
  },
  {
    id: "item-11",
    name: "KP Mixed Nuts (2kg bag)",
    image: "/placeholder-item.svg",
    price: 28.00,
    quantity: 2,
    expirationDate: "2026-09-01",
    categoryId: "cat-4",
  },
  {
    id: "item-12",
    name: "Nature Valley Bars (48-count)",
    image: "/placeholder-item.svg",
    price: 14.50,
    quantity: 70,
    expirationDate: "2026-08-30",
    categoryId: "cat-4",
  },
  {
    id: "item-13",
    name: "Frozen Chicken Breast (5kg)",
    image: "/placeholder-item.svg",
    price: 24.99,
    quantity: 35,
    expirationDate: "2026-09-15",
    categoryId: "cat-5",
  },
  {
    id: "item-14",
    name: "Frozen Mixed Vegetables (2.5kg)",
    image: "/placeholder-item.svg",
    price: 7.49,
    quantity: 90,
    expirationDate: "2026-11-01",
    categoryId: "cat-5",
  },
  {
    id: "item-15",
    name: "Ben & Jerry's Tubs (500ml, 8-pack)",
    image: "/placeholder-item.svg",
    price: 22.99,
    quantity: 5,
    expirationDate: "2026-06-01",
    categoryId: "cat-5",
  },
];

export const shops: Shop[] = [
  {
    id: "shop-1",
    name: "Borough Greens",
    owner: "Priya Sharma",
    location: "14 Borough High St, Southwark, London SE1 9QG",
    phone: "020 7946 0134",
    openingTime: "07:00",
    closingTime: "19:00",
  },
  {
    id: "shop-2",
    name: "Camden Fresh Foods",
    owner: "Liam O'Brien",
    location: "82 Camden High St, Camden Town, London NW1 0LT",
    phone: "020 7946 0267",
    openingTime: "06:00",
    closingTime: "20:00",
  },
  {
    id: "shop-3",
    name: "Hackney Harvest",
    owner: "Amara Osei",
    location: "33 Mare St, Hackney, London E8 4RG",
    phone: "020 7946 0389",
    openingTime: "08:00",
    closingTime: "18:00",
  },
  {
    id: "shop-4",
    name: "Brixton Corner Store",
    owner: "James Kowalski",
    location: "7 Electric Ave, Brixton, London SW9 8JP",
    phone: "020 7946 0412",
    openingTime: "09:00",
    closingTime: "17:00",
  },
];

export const orders: Order[] = [
  {
    id: "ord-1",
    shopId: "shop-1",
    date: "2026-02-25",
    lineItems: [
      { itemId: "item-1", itemName: "Organic Bananas (18kg case)", quantity: 5, unitPrice: 21.99 },
      { itemId: "item-4", itemName: "Semi-Skimmed Milk (12x2L)", quantity: 10, unitPrice: 13.99 },
      { itemId: "item-7", itemName: "Highland Spring Water (24-pack)", quantity: 20, unitPrice: 4.49 },
    ],
    total: 339.65,
  },
  {
    id: "ord-2",
    shopId: "shop-1",
    date: "2026-02-20",
    lineItems: [
      { itemId: "item-2", itemName: "Vine Tomatoes (10kg box)", quantity: 8, unitPrice: 16.50 },
      { itemId: "item-10", itemName: "Walkers Crisps Variety (48-pack)", quantity: 6, unitPrice: 17.99 },
    ],
    total: 239.94,
  },
  {
    id: "ord-3",
    shopId: "shop-2",
    date: "2026-02-24",
    lineItems: [
      { itemId: "item-9", itemName: "Coca-Cola Cans (24-pack)", quantity: 30, unitPrice: 8.99 },
      { itemId: "item-12", itemName: "Nature Valley Bars (48-count)", quantity: 15, unitPrice: 14.50 },
      { itemId: "item-13", itemName: "Frozen Chicken Breast (5kg)", quantity: 12, unitPrice: 24.99 },
    ],
    total: 787.08,
  },
  {
    id: "ord-4",
    shopId: "shop-2",
    date: "2026-02-18",
    lineItems: [
      { itemId: "item-6", itemName: "Greek Yoghurt (12-pack)", quantity: 20, unitPrice: 10.99 },
      { itemId: "item-14", itemName: "Frozen Mixed Vegetables (2.5kg)", quantity: 25, unitPrice: 7.49 },
    ],
    total: 407.05,
  },
  {
    id: "ord-5",
    shopId: "shop-3",
    date: "2026-02-26",
    lineItems: [
      { itemId: "item-3", itemName: "Maris Piper Potatoes (25kg sack)", quantity: 4, unitPrice: 12.00 },
      { itemId: "item-5", itemName: "Cathedral City Cheddar (2.5kg block)", quantity: 8, unitPrice: 18.50 },
      { itemId: "item-8", itemName: "Tropicana Orange Juice (12x1L)", quantity: 6, unitPrice: 24.00 },
    ],
    total: 340.00,
  },
  {
    id: "ord-6",
    shopId: "shop-3",
    date: "2026-02-15",
    lineItems: [
      { itemId: "item-11", itemName: "KP Mixed Nuts (2kg bag)", quantity: 3, unitPrice: 28.00 },
      { itemId: "item-15", itemName: "Ben & Jerry's Tubs (500ml, 8-pack)", quantity: 10, unitPrice: 22.99 },
    ],
    total: 313.90,
  },
  {
    id: "ord-7",
    shopId: "shop-4",
    date: "2026-02-22",
    lineItems: [
      { itemId: "item-1", itemName: "Organic Bananas (18kg case)", quantity: 3, unitPrice: 21.99 },
      { itemId: "item-2", itemName: "Vine Tomatoes (10kg box)", quantity: 5, unitPrice: 16.50 },
      { itemId: "item-4", itemName: "Semi-Skimmed Milk (12x2L)", quantity: 6, unitPrice: 13.99 },
    ],
    total: 232.41,
  },
  {
    id: "ord-8",
    shopId: "shop-4",
    date: "2026-02-10",
    lineItems: [
      { itemId: "item-7", itemName: "Highland Spring Water (24-pack)", quantity: 40, unitPrice: 4.49 },
      { itemId: "item-9", itemName: "Coca-Cola Cans (24-pack)", quantity: 20, unitPrice: 8.99 },
    ],
    total: 359.40,
  },
];
